# Generated by Django 5.0 on 2024-01-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('payment_online', 'payment_online'), ('payment_on_delivery', 'payment_on_delivery')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
