# Generated by Django 5.0 on 2024-01-06 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_meal_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag', to='core.tag'),
        ),
    ]
