# Generated by Django 5.0 on 2024-01-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkoption',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='meatoption',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='size',
            name='meal',
        ),
        migrations.AddField(
            model_name='drinkoption',
            name='meal',
            field=models.ManyToManyField(to='core.meal'),
        ),
        migrations.AddField(
            model_name='meatoption',
            name='meal',
            field=models.ManyToManyField(to='core.meal'),
        ),
        migrations.AddField(
            model_name='size',
            name='meal',
            field=models.ManyToManyField(to='core.meal'),
        ),
    ]
