# Generated by Django 5.0 on 2024-01-08 02:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_drinkoption_meal_remove_meatoption_meal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='selected_drink_option',
        ),
        migrations.RemoveField(
            model_name='meatoption',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='selected_meat_option',
        ),
        migrations.RemoveField(
            model_name='size',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='selected_size',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cart')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meal')),
            ],
        ),
        migrations.DeleteModel(
            name='DrinkOption',
        ),
        migrations.DeleteModel(
            name='MeatOption',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
