# Generated by Django 5.0 on 2024-01-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_orderitem_selected_drink_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='tag',
        ),
        migrations.AddField(
            model_name='meal',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='core.tag'),
        ),
    ]
