# Generated by Django 5.0 on 2024-01-15 00:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_shippingaddress_address_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
